apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefix
  creationTimestamp: null
  name: metricsdemo
  namespace: dev
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: metricsdemo
          servicePort: 3000
        path: /
    host: training-user-26.training.weave.works
status:
  loadBalancer: {}